version: '0.1'

services:
  auth-service:
    container_name: auth-service
    restart: always
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    env_file:
      - ./.env-files/auth-service.env
  
  application-gateway-service:
    container_name: application-gateway-service
    restart: always
    build:
      context: ./application-gateway-service
      dockerfile: Dockerfile
    external_links:
      - auth-service
    depends_on:
      - auth-service
    ports:
      - 80:80